### ISSUE TITLE
Error when saving Candidate profile 

### ISSUE THREAD

**Issue by madvas** [district0x/ethlance#380]
Got this error, when trying to set up a candidate profile. 

![image](https://github.com/district0x/ethlance/assets/3857155/c2a316fe-e18f-42d1-bc49-93a9fb6eb621)

```
"GraphQLError: Syntax Error: Unterminated string.\n    at f.syntaxError (https://ethlance.qa.district0x.io/js/main.js:5612:125)\n    at c (https://ethlance.qa.district0x.io/js/main.js:5625:517)\n    at Object.m [as lookahead] (https://ethlance.qa.district0x.io/js/main.js:5618:183)\n    at Object.n [as advance] (https://ethlance.qa.district0x.io/js/main.js:5618:101)\n    at Y (https://ethlance.qa.district0x.io/js/main.js:5650:47)\n    at C (https://ethlance.qa.district0x.io/js/main.js:5636:174)\n    at t (https://ethlance.qa.district0x.io/js/main.js:5635:21)\n    at ja (https://ethlance.qa.district0x.io/js/main.js:5651:40)\n    at p (https://ethlance.qa.district0x.io/js/main.js:5634:375)\n    at g (https://ethlance.qa.district0x.io/js/main.js:5634:206)"
```

This is bio: 

```
I am a freelance software developer with over 8 years of experience in the tech industry. My journey in the field has been marked by a deep passion for technology and an unwavering dedication to solving complex problems through innovative digital solutions. I specialize in full-stack development, taking pride in my ability to bridge the gap between user-friendly front-end designs and robust back-end systems.

My skill set is diverse and comprehensive. I am proficient in several programming languages, including JavaScript, Python, Ruby, and Java. In terms of front-end development, I have extensive experience with HTML5, CSS3, and JavaScript frameworks such as React.js, Vue.js, and Angular. On the back-end side, I am skilled in using Node.js, Express, Django, Ruby on Rails, and Spring Boot to create scalable and efficient applications.

Database management is another area of my expertise, with proficiency in PostgreSQL, MySQL, MongoDB, and Firebase. I also have a solid background in DevOps and cloud services, working comfortably with AWS, Google Cloud Platform, Docker, and Kubernetes to ensure seamless deployment and scalability of applications. Version control is an essential part of my workflow, and I am proficient in using Git and GitHub.

Over the years, I have worked on a wide range of projects, from developing scalable e-commerce platforms for startups to creating data-driven applications for established corporations. My approach to project management is flexible, with a preference for agile methodologies, including Scrum and Kanban, to ensure timely delivery and high-quality results.

Being a freelancer has allowed me the opportunity to collaborate with a diverse set of clients, helping me to continuously grow my skills and adapt to new challenges. I am always on the lookout for exciting projects where I can contribute my expertise and help bring innovative ideas to life.
```

**Comment by madis** [comment]
Will be fixed by https://github.com/district0x/graphql-query/pull/11
